version: '3.8'

services:
  pipeline:
    build: .
    container_name: code-smell-pipeline
    volumes:
      - ./.env:/app/.env
      - ./dataset_output:/app/dataset_output
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    # Tùy chỉnh để tăng performance
    deploy:
      resources:
        limits:
          cpus: '0.90' # Có thể set 100% nếu cloud cho phép
